version: 0.2

phases:
  install:
    runtime-versions:
      go: 1.21  # Specify the desired Go version

  pre_build:
    commands:
      - go mod download

  build:
    commands:
      - go build -o iac-signalr-linux

artifacts:
  files:
    - iac-signalr-linux
    - signalRconfig.json
    - public/*